# Generated by Django 2.2.28 on 2023-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230629_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='asfasfdas',
        ),
        migrations.AddField(
            model_name='user',
            name='rename',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
